# Telegram_Anwer Official Signing & Credentials
RELEASE_STORE_PASSWORD=772997043a**
RELEASE_KEY_ALIAS=Telegram_Anwer
RELEASE_KEY_PASSWORD=772997043a**

# Architecture and SDK setup
APP_NAME=Telegram_Anwer
API_ID=22043994
API_HASH=56f64582b363d367280db96586b97801
ANDROID_SDK_VERSION=35
ANDROID_NDK_VERSION=27.2.12479018
ANDROID_STUDIO_VERSION=2025.1.4

# Gradle Optimization Settings
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true
